# Please, also install your favorite libraries in the environment

name: frankenbody

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - pandas
  - scikit-learn
  - matplotlib
  - pyarrow
  - cryptography

  # for people who might like bioinformatics
  - biotite

  # for who like notebooks
  - jupyter-lab

  - pytest

  # to manipulate our own repo
  - git
  - gitpython

  - pip:
    - "-e ."
