# Feel free to add your favorite libraries to the environment

name: frankenbody

channels:
  - conda-forge
  - nodefaults

dependencies:
  # basic dependencies
  - python
  - pip
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - matplotlib

  # challenge logistics
  - cryptography
  - argh
  - git
  - git-lfs
  - gitpython

  # for people who like bioinformatics
  # - biotite

  # for people who like notebooks
  # - jupyter-lab

  # for people who like to test
  # - pytest

  - pip:
    - "-e ."
